import Head from 'next/head'
import AuthPage from "../../components/AuthPage";
import PinInput from "react-pin-input";
import ButtonComp from "../../components/ButtonComp";
import { useState } from "react";
import { useRouter } from "next/dist/client/router";
import { AiOutlineCheck } from 'react-icons/ai'
import { useDispatch, useSelector } from "react-redux";
import { signup } from "../../redux/actions/auth";

const Pin = () => {
  const [test, setTest] = useState('');
  const [status, setStatus] = useState(false);

  const dispatch = useDispatch();

  const { registerUser } = useSelector(state => state);

  const route = useRouter();

  let pin;
  const handleConfirm = (e) => {
    e.preventDefault();
    const { fullName, email, password } = registerUser.dataRegist;
    setStatus(true);
    dispatch(signup(fullName, email, password, Number(test)));
    // console.log(fullName, email, password, Number(test))
    // if (Number(test) === 123456) {
    //   setStatus(true);
    //   dispatch(signup(fullName, email, password, Number(test)));
    // } else {
    //   alert('Wrong code input')
    // }
  }
  return (
    <div>
      <Head>
        <title>Go-Wallet | Create PIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <AuthPage
      info={status ?
        <div className="my-5">
          <div className="badge bg-primary rounded rounded-pill py-2 my-5">
            <AiOutlineCheck className="fs-1 fw-bold text-center"/>
          </div>
          <h2>Your PIN Was Successfully Created</h2>
          <p className="my-5">Your PIN was successfully created and you can now access all the features in Go - Wallet. Login to your new account and start exploring!</p>
        </div>
        : <>
          <h2>Secure Your Account, Your Wallet, and Your Data With 6 Digits PIN That You Created Yourself.</h2>
          <p className="my-5">Create 6 digits pin to secure all your money and your data in Go - Wallet app. Keep it secret and don’t tell anyone about your Go - Wallet account password and the PIN.</p>
        </>
      }
      form={status
        ?  <div className="mt-5">
            <ButtonComp event={e => route.push('/login')} block='true'>Login Now</ButtonComp>
          </div>
        : <form>
          <PinInput 
          length={6} 
          focus
          ref={(n) => (pin = n)}
          onChange={(value, index) => {setTest(value)}}
          type="numeric" 
          inputMode="number"
          style={{padding: '10px'}}  
          inputStyle={{borderColor: 'white', color: 'black'}}
          inputFocusStyle={{borderColor: 'black'}}
          autoSelect={true}
          regexCriteria={/^[ A-Za-z0-9_@./#&+-]*$/}
          />
          <div className="mt-5">
            <ButtonComp event={handleConfirm} block='true'>Confirm</ButtonComp>
          </div>
        </form>
      }
    />
    </div>
  )
}

export default Pin;
