import Head from 'next/head';
import Layout from '../components/Layout';
import styles from '../styles/Dashboard.module.css';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { Row, Col } from 'react-bootstrap';
import SideBar from '../components/SideBar';
import { BsArrowUp } from 'react-icons/bs';
import ChartCard from '../components/ChartCard';
import HistoriesList from '../components/HistoriesList';
import histories from '../data/histories';

const Dashboard = () => {
  const route = useRouter();

  const toHistories = (e) => {
    e.preventDefault();
    route.push('/histories');
  }

  return (
    <Layout>
      <Head>
        <title>ZWallet | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.contain} container`}>
        <Row className=''>
          <aside className='col-lg-4'>
            <SideBar />
          </aside>
          <section className='col-lg-8'>
            <div className='card p-4 bg-primary'>
              <Row className='text-light'>
                <Col xs={12} md={6} className='d-flex justify-content-between flex-column'>
                  <div>Balance</div>
                  <h2>Rp120.000</h2>
                  <div>+62 813-9387-7946</div>
                </Col>
                <Col xs={12} md={6} className='d-flex justify-content-end'>
                  <div className='d-flex flex-column'>
                    <Link href='/transfer' className=' d-flex flex-row align-items-center my-2'>
                      <a className='text-decoration-none text-white my-2 py-3 px-5 bg-secondary btn'>
                        <BsArrowUp className='fs-5 me-2 text-dark'/>
                        <span className='text-dark'>Transfer</span>
                      </a>
                    </Link>
                    <Link href='/top-up' className=' d-flex flex-row align-items-center my-2'>
                      <a className='text-decoration-none text-white my-2 py-3 px-5 bg-secondary btn'>
                        <BsArrowUp className='fs-5 me-2 text-dark'/>
                        <span className='text-dark'>Top Up</span>
                      </a>
                    </Link>
                  </div>
                </Col>
              </Row>
            </div>
            <Row>
              <Col xs={12} lg={6} className='mt-3'>
                <div className='card bg-primary py-3 h-100'>
                  <ChartCard dataChart={[10, 30, 50, 70, 90, 110, 200]} labels={['Sat','Sun','Mon','Tue', 'Wed', 'Thu', 'Fri']} income={1200000} expense={800000} />
                </div>
              </Col>
              <Col xs={12} lg={6} className='mt-3'>
                <div onClick={toHistories} className={`${styles.histories} card bg-primary p-3 h-100`}>
                  <h4 className='text-light'>Transaction History</h4>
                  {histories.map((data, index) => {
                    return (index < 4 &&  <HistoriesList key={index} image={data.image} name={data.name} status={data.status} total={data.total} />)
                  })}
                </div>
              </Col>
            </Row>
          </section>
        </Row>
      </main>
    </Layout>
  )
}

export default Dashboard
